export type MovieType = {
  id: number;
  title: string;
  title_episode: string | null;
  title_uri: string | null;
  title_original: string | null;
  description: string | null;
  description_large: string | null;
  short_description: string | null;
  image_large: string | null;
  image_medium: string | null;
  image_small: string | null;
  image_still: string | null;
  image_background: string | null;
  url_imagen_t1: string | null;
  url_imagen_t2: string | null;
  image_base_horizontal: string | null;
  image_base_vertical: string | null;
  image_base_square: string | null;
  image_clean_horizontal: string | null;
  image_clean_vertical: string | null;
  image_clean_square: string | null;
  image_sprites: string | null;
  image_frames: string | null;
  image_trickplay: string | null;
  image_external: string | null;
  duration: string | null;
  date: string | null;
  year: string | null;
  preview: string | null;
  season_number: string | null;
  episode_number: string | null;
  format_types: string | null;
  live_enabled: string | null;
  live_type: string | null;
  live_ref: string | null;
  timeshift: string | null;
  votes_average: number | null;
  rating_code: string | null;
  proveedor_name: string | null;
  proveedor_code: string | null;
  encoder_technology: {
    id: number | null;
    desc: any;
  };
  recorder_technology: {
    id: number | null;
    desc: any;
  };
  resource_name: string | null;
  rollingcreditstime: string | null;
  rollingcreditstimedb: string | null;
  is_series: boolean | null;
  channel_number: number | null;
};
